### ISSUE TITLE
Please update the link in the docs

### ISSUE THREAD

**Issue by aditbharadwaj** [ionic-team/CapacitorWatch#31]
Hi the docs are really useful and descriptive, can you please update the link for the package capacitor background runner plugin? 

![image](https://github.com/ionic-team/CapacitorWatch/assets/6751554/1d977c10-d6b8-421e-aa62-2bdc2bae85f5)

thanks

**Comment by giralte-ionic** [comment]
This issue should be fixed by the 0.1.8 release
